const GET_ALL_USERS = "user:GET_ALL_USERS";
const DELETE_USER = "user:DELETE_USER";
const GET_ALL_ADMINS = "user:GET_ALL_ADMINS";
const UPDATE_PROFILE = "user:UPDATE_PROFILE";
const DEACTIVATE_ACCOUNT = "user:DEACTIVATE_ACCOUNT";


module.exports = {
    GET_ALL_USERS,
    DELETE_USER,
    GET_ALL_ADMINS,
    UPDATE_PROFILE,
    DEACTIVATE_ACCOUNT
}

